# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Виртуальная машина с Prometheus и Grafana
    config.vm.define "monitoring" do |monitoring|
      monitoring.vm.box = "ubuntu/focal64"
      monitoring.vm.hostname = "monitoring"
      # Назначение приватного IP-адреса
      monitoring.vm.network "private_network", ip: "192.168.33.10"
  
      monitoring.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu-prometheus-grafana"
        vb.memory = 4096  # 4 ГБ ОЗУ
        vb.cpus = 2       # 2 CPU
      end
    end
  
    # Вторая виртуальная машина для мониторинга
    config.vm.define "target" do |target|
      target.vm.box = "ubuntu/focal64"
      target.vm.hostname = "target"
      # Назначение приватного IP-адреса
      target.vm.network "private_network", ip: "192.168.33.11"
  
      target.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu-target"
        vb.memory = 1024  # Минимальные ресурсы, например 1 ГБ ОЗУ
        vb.cpus = 1       # 1 CPU
      end
    end
  end
  