MACHINES = {
  pam: {
    box_name: "ubuntu/jammy64",
    cpus: 2,
    memory: 1024,
    ip: "192.168.57.10"
    # Если требуется, можно добавить :box_version и другие параметры.
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем синхронизированную папку по умолчанию
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Настраиваем приватную сеть с указанным IP-адресом
    config.vm.network "private_network", ip: boxconfig[:ip]

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      
      # Опционально задаём box_version, если она задана в конфигурации
      box.vm.box_version = boxconfig[:box_version] if boxconfig.key?(:box_version)
      
      box.vm.host_name = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Провиженинг: добавляем PasswordAuthentication yes в конец файла /etc/ssh/sshd_config
      # Последняя настройка будет иметь приоритет при парсинге конфигурации SSH.
      box.vm.provision "shell", inline: <<-SHELL, privileged: true
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
        systemctl restart sshd.service
      SHELL
    end
  end
end
