# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Настройки первой виртуальной машины
  config.vm.define "ubuntu01" do |machine1|
    machine1.vm.box = "ubuntu/jammy64" # Используем образ Ubuntu 22.04
    machine1.vm.network "public_network", ip: "192.168.1.101" # Настройка сетевого интерфейса типа "мост"
    machine1.vm.hostname = "ubuntu01" # Установка имени хоста
    machine1.vm.provider "virtualbox" do |vb|
      vb.cpus = 2 # Установка количества ядер
      vb.memory = 1024 # Установка объема виртуальной памяти (в МБ)
      vb.gui = false # Отключение графического интерфейса
    end

    # Запуск скрипта provision01.sh
    machine1.vm.provision "shell", path: "provision01.sh"
  end

  # Настройки второй виртуальной машины
  config.vm.define "ubuntu02" do |machine2|
    machine2.vm.box = "ubuntu/jammy64" # Используем тот же образ
    machine2.vm.network "public_network", ip: "192.168.1.102" # Настройка сетевого интерфейса типа "мост"
    machine2.vm.hostname = "ubuntu02" # Установка имени хоста
    machine2.vm.provider "virtualbox" do |vb|
      vb.cpus = 2 # Установка количества ядер
      vb.memory = 1024 # Установка объема виртуальной памяти (в МБ)
      vb.gui = false # Отключение графического интерфейса
    end

    # Прокидываем общий каталог
    machine2.vm.synced_folder "./ansible", "/home/vagrant/ansible" 

    # Копирование приватного ключа
    machine2.vm.provision "file", source: "C:/Users/Admin/Documents/GitHub/Linux.Professional/hw3_Ansible/ubuntu_jammy64/.vagrant/machines/ubuntu01/virtualbox/private_key", destination: "/home/vagrant/.ssh/id_rsa2"

    # Установка правильных прав доступа к ключу
    machine2.vm.provision "shell", inline: <<-SHELL
      chmod 600 /home/vagrant/.ssh/id_rsa2
      chown vagrant:vagrant /home/vagrant/.ssh/id_rsa2
    SHELL

    # Запуск скрипта provision02.sh
    machine2.vm.provision "shell", path: "provision02.sh"
  end
end
