Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "storage01"
  config.vm.network "public_network", ip: "192.168.1.101"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = false

    # Создаем 5 дисков и привязываем их к SCSI контроллеру
    (2..6).each do |i| # Порты 2, 3, 4, 5 и 6
      vb.customize ["createhd", "--filename", "disk_#{i}.vdi", "--size", 500] # Создаем диск размером 500 МБ
      vb.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", i, "--device", 0, "--type", "hdd", "--medium", "disk_#{i}.vdi"]
    end
  end

  # Провизия для создания RAID
  config.vm.provision "shell", inline: <<-SHELL
    # Установка прав на выполнение для скрипта
    chmod +x /vagrant/create_raid.sh

    # Запуск скрипта для создания RAID
    bash /vagrant/create_raid.sh
  SHELL
end

