Vagrant.configure("2") do |config|
  # Используем образ Ubuntu Jammy 64-bit
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "storage01"
  
  # Настраиваем сетевое подключение
  config.vm.network "public_network", ip: "192.168.1.101"

  config.vm.provider "virtualbox" do |vb|
    # Настраиваем ресурсы виртуальной машины
    vb.memory = "1024" # 1 ГБ оперативной памяти
    vb.cpus = 1       # 1 CPU
    vb.gui = false    # Отключаем графический интерфейс

    # Создаем 9 дисков и привязываем их к SCSI контроллеру
    (2..10).each do |i| # Порты 2, 3, 4, 5, 6, 7, 8, 9, 10
      # Создаем диск размером 500 МБ
      vb.customize ["createhd", "--filename", "disk_#{i}.vdi", "--size", 500]
      
      # Привязываем диск к SCSI контроллеру
      vb.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", i, "--device", 0, "--type", "hdd", "--medium", "disk_#{i}.vdi"]
    end
  end

  # Установка ZFS после запуска виртуальной машины
  config.vm.provision "shell", inline: <<-SHELL
    # Обновляем систему и устанавливаем ZFS
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y zfsutils-linux

    # Проверяем установку ZFS
    zfs --version
  SHELL
end
