# Vagrantfile для AlmaLinux 9.3
Vagrant.configure("2") do |config|
    # Указываем базовый образ AlmaLinux 9.3
    config.vm.box = "bento/almalinux-9.3"
  
    # Настройки сети с статическим IP
    config.vm.network "private_network", ip: "192.168.11.101"
  
    # Настройки виртуальной машины
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # Устанавливаем объем оперативной памяти
      vb.cpus = 2        # Устанавливаем количество процессоров
      vb.name = "AlmaLinux-9.3" # Имя виртуальной машины
    end
  end
  