---
- hosts: all
  become: yes
  vars:
    nginx_port: 8080

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Copy nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload Nginx

    - name: Configure HTML page
      template:
        src: index.j2
        dest: /var/www/html/index.html
      notify: Reload Nginx

    - name: Start Nginx systemd
      systemd:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted
